
name: Upload Pyton package to docker

on:
  push:
    branches: [main]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: checkout to branch
        uses: actions/checkout@v2
    - name: Testing
      run: |
          echo "Building docker Image using action"
          ls 

    - name: Build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: haiderdocker/test-github-action
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
