
name: Upload Pyton package to docker

on:
  push:
    branches: [master]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Build and push docker image
      run: echo "Building docker Image using action"
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: haiderdocker/test-github-action
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
name: Upload Pyton package to docker

on:
  push:
    branches: [master]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Build and push docker image
      run: echo "Building docker Image using action"
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: haiderdocker/test-github-action
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
name: Upload Pyton package to docker

on:
  push:
    branches: [master]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Build and push docker image
      run: echo "Building docker Image using action"
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: haiderdocker/test-github-action
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
name: Upload Pyton package to docker

on:
  push:
    branches: [master]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Build and push docker image
      run: echo "Building docker Image using action"
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: haiderdocker/test-github-action
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
name: Upload Pyton package to docker

on:
  push:
    branches: [master]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Build and push docker image
      run: echo "Building docker Image using action"
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: haiderdocker/test-github-action
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
name: Upload Pyton package to docker

on:
  push:
    branches: [main]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Build and push docker image
      run: echo "Building docker Image using action"
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: haiderdocker/test-github-action
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}